# Generated by Django 5.2.1 on 2025-07-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('overview', models.CharField(max_length=255)),
                ('poster_path', models.CharField(blank=True, max_length=500)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
